In [2]:
#1. array type , 2 access of an array element , 3shape of an array ,4 type of element in array 

import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])
x = a+b

print(x)
print(x.ndim)
print(x.shape)
print(x.size)
print(x.T)


[[ 2  4  6]
 [ 8 10 12]]
2
(2, 3)
6
[[ 2  8]
 [ 4 10]
 [ 6 12]]


In [3]:
# a) reshape (2,2,3) b) sequence of integers frin 3 to 30 with step 5 and reshape  3X2  c) flatten array d) 3*4 with zeros array in numpy 

import numpy as np

# a) Reshape (2, 2, 3)
array_1 = np.arange(12)  # Create an array with 12 elements (0 to 11)
reshaped_array_1 = array_1.reshape(2, 2, 3)
print(reshaped_array_1)

# b) Sequence from 3 to 30 with step 5 and reshape to 3x2
array_2 = np.arange(3, 31, 5)  # Create a sequence from 3 to 30 with step 5
reshaped_array_2 = array_2.reshape(3, 2)
print(reshaped_array_2)

# c) Flatten the reshaped array (from part b)
flattened_array = reshaped_array_2.flatten()
print( flattened_array)

# d) 3x4 array of zeros
zeros_array = np.zeros((3, 4))
print( zeros_array)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[ 3  8]
 [13 18]
 [23 28]]
[ 3  8 13 18 23 28]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# matrix multiplication in numpy

import numpy as np

# Define two matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Matrix multiplication using np.dot()
result = np.dot(A, B)

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nResult of np.dot(A, B):")
print(result)



In [18]:
import numpy as np

R = int(input("Enter the number of rows for Matrix 1: "))
C = int(input("Enter the number of columns for Matrix 1: "))
matrix1 = []

for i in range(R):
    row = list(map(int, input(f"Enter row {i+1} (space-separated): ").split()))
    matrix1.append(row)

m1 = np.array(matrix1)
print("\nMatrix 1:")
print(m1)

R1 = int(input("Enter the number of rows for Matrix 2: "))
C1 = int(input("Enter the number of columns for Matrix 2: "))
matrix2 = []

for i in range(R1):
    row = list(map(int, input(f"Enter row {i+1} (space-separated): ").split()))
    matrix2.append(row)

m2 = np.array(matrix2)
print("\nMatrix 2:")
print(m2)

if C == R1:
    result = m1.dot(m2)
    print("\nMatrix multiplication result:")
    print(result)

    print("\nTranspose of the result:")
    print(result.T)
else:
    print("\nMatrix multiplication is not possible. The number of columns in Matrix 1 must equal the number of rows in Matrix 2.")


Matrix 1:
[[1 2 3]
 [4 5 6]]

Matrix 2:
[[ 7  8]
 [ 9 10]
 [11 12]]

Matrix multiplication result:
[[ 58  64]
 [139 154]]

Transpose of the result:
[[ 58 139]
 [ 64 154]]


In [20]:
import numpy as np

# Creating arrays of ones and zeros
ones = np.ones((2, 3))  # 2x3 array of ones
zeros = np.zeros((2, 3))  # 2x3 array of zeros


# Horizontal stacking (hstack)
hstack_result = np.hstack((ones, zeros))
print("\nHorizontal Stack (hstack):")
print(hstack_result)

# Vertical stacking (vstack)
vstack_result = np.vstack((ones, zeros))
print("\nVertical Stack (vstack):")
print(vstack_result)

# Depth stacking (dstack)
dstack_result = np.dstack((ones, zeros))
print("\nDepth Stack (dstack):")
print(dstack_result)


Horizontal Stack (hstack):
[[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]

Vertical Stack (vstack):
[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]

Depth Stack (dstack):
[[[1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]]]


In [24]:
import numpy as np

arr = np.arange(16).reshape(4,4)

result1 = np.hsplit(arr,2)
result2 = np.vsplit(arr,2)
result3 = np.array_split(arr,4)

print(result1)
print(result2)
print(result3)

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]
